// Generated by https://quicktype.io

import { Errors } from './errors';
import { Sort } from './fetch';

export interface CreateTagsResp {
  ok?: boolean;
  msg?: string;
  tagCreated?: TagCreated;
  errors?: Errors[];
}

export interface TagCreated {
  id: number;
  name: string;
  created_at: string;
  first_name: string;
  last_name: string;
}

export interface CreateTag {
  name: string;
  created_by: number;
}

export interface GetTagsResp {
  ok: boolean;
  msg: string;
  tags: TagCreated[];
  total: number;
}

export interface TagQuery {
  sort: Sort;
  order: TagsOrder;
  limit: number;
  from: number;
}

export type TagsOrder = 'id' | 'name' | 'created_at' | 'first_name';
