// Generated by https://quicktype.io

import { Sort, Active } from './';

export interface CountUsers {
  ok: boolean;
  msg: string;
  userType: UserType[];
}

export interface UserType {
  role: string;
  count: string;
}

export interface UserList {
  ok: boolean;
  msg: string;
  total: number;
  users: UserTable[];
}

export interface UserTable {
  id: number;
  first_name: string;
  last_name: string;
  email: string;
  phone: null | string;
  created_at: string;
  updated_at: string;
  is_active: boolean;
  role_id: number;
  role: string;
}

export interface UserQuery {
  sort: Sort;
  order: OrderByUser;
  limit: number;
  from: number;
  active: boolean;
}

export type OrderByUser =
  | 'id'
  | 'first_name'
  | 'last_name'
  | 'email'
  | 'phone'
  | 'created_at'
  | 'updated_at';

export interface GetUserResp {
  ok: boolean;
  msg: string;
  user: GetUser;
}

export interface GetUser {
  id: number;
  first_name: string;
  last_name: string;
  email: string;
  phone: string;
  created_at: string;
  updated_at: string;
  is_active: boolean;
  role_id: number;
  role: string;
}
