// Generated by https://quicktype.io

import { Errors } from './errors';
import { Sort } from './fetch';

export interface AddVariantSizeResp {
  ok: boolean;
  msg: string;
  newVariant: NewVariant;
  errors?: Errors[];
}

export interface NewVariant {
  id: number;
  name: string;
  short: string;
}

export interface VariantSize {
  name: string;
  short: string;
}

export interface GetVariantSizesResp {
  msg: string;
  ok: boolean;
  total: number;
  variants: Variant[];
}

export interface Variant {
  id: number;
  name: string;
  short: string;
}

export interface VariantColor {
  name: string;
  color: string;
}

export interface AddVariantColorResp {
  ok: boolean;
  msg: string;
  newColor: NewColor;
  errors?: Errors[];
}

export interface NewColor {
  id: number;
  name: string;
  color: string;
}

export interface VariantSizeQuery {
  sort: Sort;
  order: VariantSizeOrder;
  limit: number;
  from: number;
}

export type VariantSizeOrder = 'id' | 'name' | 'sort';

export interface GetVariantColorsResp {
  ok: boolean;
  msg: string;
  total: number;
  variantsColors: VariantsColor[];
}

export interface VariantsColor {
  id: number;
  name: string;
  color: string;
}

export interface VariantColorQuery {
  sort: Sort;
  order: VariantColorOrder;
  limit: number;
  from: number;
}

export type VariantColorOrder = 'id' | 'name' | 'color';
